import crypt

import random, string

def getSalt(chars = string.letters + string.digits):
    # generate a random 2-character 'salt'
    return random.choice(chars) + random.choice(chars)

def crackCrypt(passw):
	#accepts passw and a salt(generated by getsalt)
	saltPhrase = getSalt()
	return crypt.crypt(passw, saltPhrase)

with open('dict/brit-a-z.txt') as f:
	for line in f:
		#creating hashes and storing
		newHash = crackCrypt(line)
		hashStore = open("hashDict.txt","a")
		hashStore.write(newHash + "\r")

		#creating comparison file
		comparison = open("hashCompare.txt","a")
		comparison.write(line + "hash :" + newHash + "\n\n")
		
		if 'zymurgy' in line:
			break

print "Job's Done...."
